version: "2.0"
services:
  centos5_build:
    image: proxysql/packaging:build-centos5
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/:/root/
      - ./docker/images/proxysql/rhel-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=centos5
    command:
      - /opt/entrypoint/entrypoint.bash
  centos5_dbg_build:
    image: proxysql/packaging:build-centos5
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/:/root/
      - ./docker/images/proxysql/rhel-compliant/dbg-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=dbg-centos5
    command:
      - /opt/entrypoint/entrypoint.bash
  centos67_build:
    image: proxysql/packaging:build-centos6.7
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/:/root/
      - ./docker/images/proxysql/rhel-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=centos67
    command:
      - /opt/entrypoint/entrypoint.bash
  centos67_dbg_build:
    image: proxysql/packaging:build-centos6.7
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/:/root/
      - ./docker/images/proxysql/rhel-compliant/dbg-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=dbg-centos67
    command:
      - /opt/entrypoint/entrypoint.bash
  centos7_build:
    image: proxysql/packaging:build-centos7
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/:/root/
      - ./docker/images/proxysql/rhel-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=centos7
    command:
      - /opt/entrypoint/entrypoint.bash
  centos7_dbg_build:
    image: proxysql/packaging:build-centos7
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/:/root/
      - ./docker/images/proxysql/rhel-compliant/dbg-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=dbg-centos7
    command:
      - /opt/entrypoint/entrypoint.bash
  centos7_ch_build:
    image: proxysql/packaging:build-centos7
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/:/root/
      - ./docker/images/proxysql/rhel-compliant/ch-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=clickhouse-centos7
    command:
      - /opt/entrypoint/entrypoint.bash
  fedora24_build:
    image: proxysql/packaging:build-fedora24
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/:/root/
      - ./docker/images/proxysql/rhel-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=fedora24
    command:
      - /opt/entrypoint/entrypoint.bash
  fedora24_dbg_build:
    image: proxysql/packaging:build-fedora24
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/:/root/
      - ./docker/images/proxysql/rhel-compliant/dbg-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=dbg-fedora24
    command:
      - /opt/entrypoint/entrypoint.bash
  fedora24_ch_build:
    image: proxysql/packaging:build-fedora24
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/:/root/
      - ./docker/images/proxysql/rhel-compliant/ch-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=clickhouse-fedora24
    command:
      - /opt/entrypoint/entrypoint.bash
  fedora27_build:
    image: proxysql/packaging:build-fedora27
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/:/root/
      - ./docker/images/proxysql/rhel-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=fedora27
    command:
      - /opt/entrypoint/entrypoint.bash
  fedora27_dbg_build:
    image: proxysql/packaging:build-fedora27
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/:/root/
      - ./docker/images/proxysql/rhel-compliant/dbg-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=dbg-fedora27
    command:
      - /opt/entrypoint/entrypoint.bash
  fedora27_ch_build:
    image: proxysql/packaging:build-fedora27
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/:/root/
      - ./docker/images/proxysql/rhel-compliant/ch-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=clickhouse-fedora27
    command:
      - /opt/entrypoint/entrypoint.bash
  fedora28_build:
    image: proxysql/packaging:build-fedora28
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/:/root/
      - ./docker/images/proxysql/rhel-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=fedora28
    command:
      - /opt/entrypoint/entrypoint.bash
  fedora28_dbg_build:
    image: proxysql/packaging:build-fedora28
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/:/root/
      - ./docker/images/proxysql/rhel-compliant/dbg-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=dbg-fedora28
    command:
      - /opt/entrypoint/entrypoint.bash
  fedora28_ch_build:
    image: proxysql/packaging:build-fedora28
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/:/root/
      - ./docker/images/proxysql/rhel-compliant/ch-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=clickhouse-fedora28
    command:
      - /opt/entrypoint/entrypoint.bash
  debian7_build:
    image: proxysql/packaging:build-debian7
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=debian7
    command:
      - /opt/entrypoint/entrypoint.bash
  debian7_dbg_build:
    image: proxysql/packaging:build-debian7
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/dbg-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=dbg-debian7
    command:
      - /opt/entrypoint/entrypoint.bash
  debian8_build:
    image: proxysql/packaging:build-debian8
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=debian8
    command:
      - /opt/entrypoint/entrypoint.bash
  debian8_dbg_build:
    image: proxysql/packaging:build-debian8
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/dbg-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=dbg-debian8
    command:
      - /opt/entrypoint/entrypoint.bash
  debian9_build:
    image: proxysql/packaging:build-debian9
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=debian9
    command:
      - /opt/entrypoint/entrypoint.bash
  debian9_dbg_build:
    image: proxysql/packaging:build-debian9
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/dbg-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=dbg-debian9
    command:
      - /opt/entrypoint/entrypoint.bash
  debian9_ch_build:
    image: proxysql/packaging:build-debian9
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/ch-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=clickhouse-debian9
    command:
      - /opt/entrypoint/entrypoint.bash
  debian9.4_build:
    image: proxysql/packaging:build-debian9.4
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=debian9.4
    command:
      - /opt/entrypoint/entrypoint.bash
  debian9.4_dbg_build:
    image: proxysql/packaging:build-debian9.4
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/dbg-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=dbg-debian9.4
    command:
      - /opt/entrypoint/entrypoint.bash
  debian9.4_ch_build:
    image: proxysql/packaging:build-debian9.4
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/ch-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=clickhouse-debian9.4
    command:
      - /opt/entrypoint/entrypoint.bash
  ubuntu12_build:
    image: proxysql/packaging:build-ubuntu12
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=ubuntu12
    command:
      - /opt/entrypoint/entrypoint.bash
  ubuntu12_dbg_build:
    image: proxysql/packaging:build-ubuntu12
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/dbg-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=dbg-ubuntu12
    command:
      - /opt/entrypoint/entrypoint.bash
  ubuntu14_build:
    image: proxysql/packaging:build-ubuntu14
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=ubuntu14
    command:
      - /opt/entrypoint/entrypoint.bash
  ubuntu14_dbg_build:
    image: proxysql/packaging:build-ubuntu14
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/dbg-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=dbg-ubuntu14
    command:
      - /opt/entrypoint/entrypoint.bash
  ubuntu16_build:
    image: proxysql/packaging:build-ubuntu16
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=ubuntu16
    command:
      - /opt/entrypoint/entrypoint.bash
  ubuntu16_dbg_build:
    image: proxysql/packaging:build-ubuntu16
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/dbg-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=dbg-ubuntu16
    command:
      - /opt/entrypoint/entrypoint.bash
  ubuntu16_ch_build:
    image: proxysql/packaging:build-ubuntu16
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/ch-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=clickhouse-ubuntu16
    command:
      - /opt/entrypoint/entrypoint.bash
  ubuntu18_build:
    image: proxysql/packaging:build-ubuntu18
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=ubuntu18
    command:
      - /opt/entrypoint/entrypoint.bash
  ubuntu18_dbg_build:
    image: proxysql/packaging:build-ubuntu18
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/dbg-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=dbg-ubuntu18
    command:
      - /opt/entrypoint/entrypoint.bash
  ubuntu18_ch_build:
    image: proxysql/packaging:build-ubuntu18
    volumes:
      - ./docker/images/proxysql/deb-compliant/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/ch-entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE=clickhouse-ubuntu18
    command:
      - /opt/entrypoint/entrypoint.bash
