#  pull_request:
#    branches: [ "v2.x" ]
#  schedule:
#    - cron: '15 13 * * 3'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install build tools
      run: sudo apt-get -y install make automake git wget gcc g++ libtool equivs python3
    - name: Install build dependencies
      run: sudo apt-get -y install libssl-dev gnutls-dev libgnutls28-dev libmysqlclient-dev libboost-all-dev libunwind8 libunwind-dev uuid-dev ca-certificates
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build C++
      run: |
        export GIT_VERSION=$(git describe --long --abbrev=7)
        make clickhouse
        
