name: CI-3p-sqlalchemy
run-name: '${{ github.event.workflow_run && github.event.workflow_run.head_branch || github.ref_name }} ${{ github.workflow }} ${{ github.event.workflow_run && github.event.workflow_run.head_sha || github.sha }}'

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ CI-trigger ]
    types: [ completed ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run && github.event.workflow_run.head_branch || github.ref_name }}
  cancel-in-progress: true

jobs:
  run:
    if: ${{ github.event.workflow_run && github.event.workflow_run.conclusion == 'success' || ! github.event.workflow_run }}
    uses: sysown/proxysql/.github/workflows/ci-3p-sqlalchemy.yml@GH-Actions
    secrets: inherit
    with:
      trigger: ${{ toJson(github) }}
      infradb: ${{ vars.MATRIX_3P_SQLALCHEMY_infradb_mysql }}
      connector: ${{ vars.MATRIX_3P_SQLALCHEMY_connector_mysql }}
