name: CI-3p-django-framework

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ CI-builds ]
    types: [ completed ]
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
  
jobs:
  run:
    uses: sysown/proxysql/.github/workflows/ci-3p-django-framework.yml@GH-Actions
    secrets: inherit
    with:
      trigger: ${{ toJson(github) }}
      infradb: ${{ vars.MATRIX_3P_SQLALCHEMY_infradb_mysql }}
      connector: ${{ vars.MATRIX_3P_SQLALCHEMY_connector_mysql }}
