name: CI-builds
env:
  MAIN: refs/heads/${{ github.event.repository.default_branch }}

on:
  push:
    branches: [ $MAIN ]
    paths-ignore:
    - '.github/**'
    - '**.md'
  pull_request:
    branches: [ $MAIN ]
    paths-ignore:
    - '.github/**'
    - '**.md'
#  schedule:
#    - cron: '15 13 * * 3'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  run:
    uses: sysown/proxysql/.github/workflows/ci-builds.yml@GH-Actions
    secrets: inherit
    
