name: CI-maketest

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ CI-builds ]
    types: [ completed ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  run:
    uses: sysown/proxysql/.github/workflows/ci-maketest.yml@GH-Actions
    secrets: inherit
    with:
      trigger: ${{ toJson(github) }}
      target: ${{ vars.MATRIX_MAKETEST_target }}
