name: CI-package-build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  clean:
    runs-on: ubuntu-22.04
    steps:
    - name: Clean packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # gh release delete-asset v2.x-head
        gh release delete v2.x-head --repo ${{ github.repository }} --cleanup-tag || true
        gh release create v2.x-head --repo ${{ github.repository }} --title v2.x-head --draft --prerelease --notes-file - << EOF
        ## Development Snapshot
        
        GH-Action Package-Build on PR merge into v2.x
        
        Started : **$(date '+%Y-%m-%d %H:%M:%S %Z')**
        
        Status : **Build in progress**
        EOF

    - name: Clean repo
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.REPO_HOST }}
        username: ${{ secrets.REPO_USER }}
        key: ${{ secrets.REPO_PRIVATE_KEY }}
        script: |
          ls -1 ${{ secrets.REPO_TARGET }} | sort -rV | tail +6 | xargs -n1 rm -rf
    
  build:
    runs-on: ubuntu-22.04
    needs: [ clean ]
    strategy:
      fail-fast: false
      matrix:
#        dist: [ 'centos7' ]
        dist: [ 'almalinux8','almalinux9','centos7','centos8','centos9','debian10','debian11','debian12','fedora38','fedora39','opensuse15','ubuntu16','ubuntu18','ubuntu20','ubuntu22' ]
        type: [ '','-dbg','-clang' ]
        exclude:
#         broken - clang too old
          - dist: 'centos7'
            type: '-clang'
          - dist: 'debian10'
            type: '-clang'
          - dist: 'ubuntu16'
            type: '-clang'
          - dist: 'ubuntu18'
            type: '-clang'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: 'sysown/proxysql'
#        ref: 'v2.x'
        fetch-depth: 0
      
    - name: Set GIT_VERSION
      run: |
        git fetch --tags --force
        echo "GIT_VERSION=$(git describe --long --abbrev=7)" >> $GITHUB_ENV
    
    - name: Update release
      if: ${{ !cancelled() }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [[ "${{ matrix.dist }}" = "centos7" ]] && [[ "${{ matrix.type }}" = "" ]]; then
        gh release edit v2.x-head --draft --prerelease --repo ${{ github.repository }} --tag v2.x-head --title "v2.x-head - ${GIT_VERSION}" --notes-file - << EOF
        ## Development Snapshot
        
        GH-Action Package-Build on PR merge into v2.x
        
        Updated : **$(date '+%Y-%m-%d %H:%M:%S %Z')**
        
        Status : **Build in progress**
        EOF
        fi
    
    - name: Build package
      run: |
        make ${{ matrix.dist }}${{ matrix.type }}
        echo "BIN_PKG=$(ls -1 binaries/*[mb])" >> $GITHUB_ENV
        echo "BIN_HASH=$(ls -1 binaries/*.id-hash)" >> $GITHUB_ENV
    
    - name: Deploy to Repo
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.REPO_PRIVATE_KEY }}
          ARGS: "-aic"
          SOURCE: ${{ env.BIN_PKG }}
          REMOTE_HOST: ${{ secrets.REPO_HOST }}
          REMOTE_USER: ${{ secrets.REPO_USER }}
          TARGET: ${{ secrets.REPO_TARGET }}/binaries-${{ env.GIT_VERSION }}/
          EXCLUDE: binaries/.gitignore
    
    - name: Push packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # git tag --force -a v2.x-head -m 'GH-Actions - Development Snapshot Build'
        # git push origin --tags
        # gh release upload v2.x-head --repo ${{ github.repository }} --clobber binaries/proxysql*${{ matrix.dist }}*[mb]
        gh release upload v2.x-head --repo ${{ github.repository }} --clobber ${{ env.BIN_PKG }}
    
#    - name: Archive artifacts
#      if: ${{ failure() && !cancelled() }}
#      uses: actions/upload-artifact@v4
#      with:
#        name: ${{ github.workflow }}-${{ env.GIT_VERSION }}-${{ matrix.dist }}
#        path: |
#          ./binaries/
#          !./**/.gitignore
    
  finalize:
    runs-on: ubuntu-22.04
    needs: [ build ]
    steps:
    - name: Update release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release edit v2.x-head --draft --prerelease --repo ${{ github.repository }} --tag v2.x-head --notes-file - << EOF
        ## Development Snapshot
        
        GH-Action Package-Build on PR merge into v2.x
        
        Finished : **$(date '+%Y-%m-%d %H:%M:%S %Z')**
        
        Status : **Build is finished**
        
        [![Package-Build](https://github.com/${{ github.repository }}/actions/workflows/ci-package-build.yml/badge.svg)](https://github.com/${{ github.repository }}/actions/workflows/ci-package-build.yml)
        
        EOF
        
