name: CI-selftests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        testdist: [ 'ubuntu22' ]
#        infradb: [ 'mysql57', 'mysql80', 'mysql81', 'mysql82', 'mariadb10', 'mariadb11' ]
        infradb: [ 'mysql57' ]
    env:
      TESTDIST: ${{ matrix.testdist }}
      INFRADB:  ${{ matrix.infradb }}
      BLDCACHE: CI-builds_${{ github.sha }}_${{ matrix.testdist }}-tap_src
      BASELINE: ${{ vars[format('BASELINE_3P_MARIADB_CONNECTOR_C_{0}', matrix.infradb)] }}

    steps:
    - name: Cache restore src
      id: cache-src
      uses: actions/cache/restore@v4
      with:
        key: CI-builds_${{ github.sha }}_ubuntu22-tap_src
        fail-on-cache-miss: true
        path: |
          proxysql/src/

    - name: Run proxysql
      run: |
        #set -x
        set +e
        ulimit -c unlimited
        
        cd ${{ github.workspace }}/proxysql
        mkdir -p ci_infra_logs/regular_infra/proxysql
        cd src
        mkdir coverage_reports

        #(./proxysql --clickhouse-server --sqlite3-server --idle-threads -f -c "$DOCKER_SCRIPT_PATH/conf/proxysql/proxysql.cnf" -D $REGULAR_INFRA_DATADIR &> $REGULAR_INFRA_DATADIR/proxysql.log) &
        (./proxysql -f --initial --clickhouse --idle-threads -D . &>proxysql.log &)
        sleep 10
        mysql -uadmin -padmin -h127.0.0.1 -P6032 -e "SELECT version();" 2>&1 | grep -v 'Using a password'

    - name: Self-tests
      run: |
        #set -x
        set +e
        set -o pipefail
        ulimit -c unlimited
        cd ${{ github.workspace }}/proxysql/src

        mysql -V -vvv
        mysql -uadmin -padmin -h127.0.0.1 -P6032 -vvv -e "SELECT version();" 2>&1 | grep -v 'Using a password'
        mysql -uadmin -padmin -h127.0.0.1 -P6032 -vvv -e "SET mysql-verbose_query_error=true;" 2>&1 | grep -v 'Using a password'
        
        mysql -uadmin -padmin -h127.0.0.1 -P6032 -vvv -e "PROXYSQL COREDUMP;" 2>&1 | grep -v 'Using a password'
        (ls -l ./core* && file ./core* && rm ./core*) || exit 1
        mysql -uadmin -padmin -h127.0.0.1 -P6032 -vvv -e "PROXYSQL COMPRESSEDCOREDUMP;" 2>&1 | grep -v 'Using a password'
        (ls -l ./core* && file ./core* && rm ./core*) || exit 1
        
        mysql -uadmin -padmin -h127.0.0.1 -P6032 -vvv 2>&1 << EOF | grep -v 'Using a password'
        SELECT COUNT(*) FROM stats_mysql_query_digest;
        SELECT COUNT(*) FROM stats_mysql_query_digest_reset;
        SELECT schemaname, COUNT(*) FROM stats_mysql_query_digest GROUP BY schemaname;
        SELECT schemaname, COUNT(*) FROM stats_mysql_query_digest_reset GROUP BY schemaname;
        TRUNCATE TABLE stats.stats_mysql_query_digest_reset;
        TRUNCATE TABLE stats.stats_mysql_query_digest;
        PROXYSQLTEST 1 1000;
        PROXYSQLTEST 2 1000;
        PROXYSQLTEST 3 1000;
        PROXYSQLTEST 4 1000;
        PROXYSQLTEST 5 1000;
        PROXYSQLTEST 6 1000;
        EOF
        RC=$?
        
        echo 'DONE'
        exit $RC

    - name: Cleanup
      if: ${{ always() }}
      run: |
        set +e
        
        mysql -h127.0.0.1 -P6032 -uadmin -padmin -e "PROXYSQL SHUTDOWN SLOW" &> /dev/null
        sleep 10
        killall proxysql
        
        sudo chmod -R 777 ${{ github.workspace }}/*

    - name: Archive artifacts logs
      if: ${{ failure() && !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.workflow }}-${{ github.sha }}-logs-run#${{ github.run_number }}
        path: |
          proxysql/ci_*_logs/
          
    - name: Archive artifacts bin
      if: ${{ failure() && !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.workflow }}-${{ github.sha }}-bin-run#${{ github.run_number }}
        path: |
          proxysql/binaries/
          proxysql/src/
          proxysql/libs/
#          proxysql/deps/
          
